In [1]:
import numpy as np
np.__version__

'1.22.4'

In [2]:
# creating  a random numpy array
x = np.random.randint(10, size=(3,4,5))
x

array([[[9, 3, 8, 2, 3],
        [1, 3, 3, 9, 5],
        [6, 2, 8, 5, 5],
        [8, 6, 3, 6, 0]],

       [[9, 2, 4, 0, 0],
        [2, 4, 3, 1, 4],
        [6, 5, 7, 8, 7],
        [1, 3, 4, 6, 2]],

       [[2, 4, 0, 5, 5],
        [8, 2, 6, 5, 8],
        [4, 9, 5, 5, 5],
        [7, 9, 3, 7, 2]]])

In [3]:
# to see the number of dimentions of a numpy object
x.ndim

3

In [4]:
# to see the shape of the object
x.shape

(3, 4, 5)

In [5]:
x.size # to see the size

60

In [6]:
x.dtype # will return the data type

dtype('int64')

In [7]:
x.itemsize # will return how big of this data type is in this case 8 bytes

8

In [8]:
x.nbytes # will return the total bytes of the total size

480

Creating numpy array


In [9]:
x = np.array(object=[1,2,3,4,5])
type(x)

numpy.ndarray

In [10]:
y = np.array(object=[1,2,3,4,5,6,7])
y.dtype

dtype('int64')

Creating array from scratch


In [11]:
np.zeros((4,5), dtype='int') # this will return zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
np.ones((4,5)) # this will return the values in ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full(shape=(4,4), fill_value= 3.1416) # a nice way to do all the things in one code

array([[3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416]])

In [14]:
np.arange(0,20,2) #arange([start,] stop[, step,], dtype=None, *, like=None)




array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.arange(1,25,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [16]:
np.linspace(0,1,5) #Returns num evenly spaced samples, calculated over the interval [start, stop].

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.random.random((2,3))

array([[0.6765702 , 0.86428027, 0.25194004],
       [0.52852419, 0.2510895 , 0.19707547]])

In [18]:
#randint(low, high=None, size=None, dtype=int)

#Return random integers from low (inclusive) to high (exclusive)
np.random.randint(10,100, size=(3,4))

array([[67, 61, 98, 21],
       [13, 14, 75, 12],
       [12, 75, 50, 24]])

In [19]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Datatypes
1. bool
2. int
3. complex
4. float
5. object


In [20]:
x = np.random.randint(10,100,(4,3))
x

array([[12, 85, 12],
       [65, 59, 99],
       [46, 46, 42],
       [10, 23, 34]])

In [21]:
x[1,2]

99

In [22]:
x[2]

array([46, 46, 42])

In [23]:
x[-1,-2]

23

In [24]:
x[1:3]

array([[65, 59, 99],
       [46, 46, 42]])

In [25]:
x[1:3, 1:2]

array([[59],
       [46]])

In [26]:
np.random.seed(6)
y = np.random.randint(0,1000,(7,7))
y

array([[906, 713, 227, 980, 618, 365, 335],
       [362, 848, 318, 281, 513,  75, 333],
       [697,  26, 495, 161, 748, 622, 324],
       [929, 264, 130, 204, 980, 987,  31],
       [450, 901, 637, 410, 527, 473, 342],
       [626, 939, 197, 485, 433, 644, 485],
       [ 62, 592, 194, 127, 322, 319, 147]])

In [27]:
y[2:6,2]

array([495, 130, 637, 197])

[start, stop, step]


In [28]:
y[1:7:2, 1:7:2]

array([[848, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

Array slicing as views

In [29]:
a = y[1:7:2, 1:7:2]

In [30]:
a[0,0] = 999

In [31]:
a

array([[999, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

In [32]:
y # this will change the original y as well

array([[906, 713, 227, 980, 618, 365, 335],
       [362, 999, 318, 281, 513,  75, 333],
       [697,  26, 495, 161, 748, 622, 324],
       [929, 264, 130, 204, 980, 987,  31],
       [450, 901, 637, 410, 527, 473, 342],
       [626, 939, 197, 485, 433, 644, 485],
       [ 62, 592, 194, 127, 322, 319, 147]])

In [33]:
#incase if we dont want to change the data in y then we must copy it first
a =y[1:7:2, 1:7:2].copy()
a

array([[999, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

In [34]:
a[0,0] = 100
a

array([[100, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

In [35]:
y # in this way it will not change

array([[906, 713, 227, 980, 618, 365, 335],
       [362, 999, 318, 281, 513,  75, 333],
       [697,  26, 495, 161, 748, 622, 324],
       [929, 264, 130, 204, 980, 987,  31],
       [450, 901, 637, 410, 527, 473, 342],
       [626, 939, 197, 485, 433, 644, 485],
       [ 62, 592, 194, 127, 322, 319, 147]])

In [36]:
y.shape

(7, 7)

In [37]:
z = np.random.randint(0,100,size=(5,6))
z

array([[85, 28, 43, 57,  5, 50],
       [26, 78, 40, 69, 70, 90],
       [63, 10, 67, 85, 11,  1],
       [82, 35, 22, 41, 24, 48],
       [42, 67,  7, 36, 75, 56]])

In [38]:
# to change the data shape 
#but it has to be the same size of numbers
z.reshape(6,5)

array([[85, 28, 43, 57,  5],
       [50, 26, 78, 40, 69],
       [70, 90, 63, 10, 67],
       [85, 11,  1, 82, 35],
       [22, 41, 24, 48, 42],
       [67,  7, 36, 75, 56]])

Concatenate

In [39]:
np.random.seed(0)
a = np.random.randint(0,100,size=(2,3))
b = np.random.randint(5,500,size=(2,3))



In [40]:
a

array([[44, 47, 64],
       [67, 67,  9]])

In [41]:
b

array([[216, 282, 247],
       [297,  92,  75]])

In [42]:
np.concatenate([a,b])

array([[ 44,  47,  64],
       [ 67,  67,   9],
       [216, 282, 247],
       [297,  92,  75]])

In [43]:
# to place one array next to other one
np.concatenate([a,b], axis=1)

array([[ 44,  47,  64, 216, 282, 247],
       [ 67,  67,   9, 297,  92,  75]])

In [44]:
np.vstack([a,b])

array([[ 44,  47,  64],
       [ 67,  67,   9],
       [216, 282, 247],
       [297,  92,  75]])

In [45]:
np.hstack([a,b])

array([[ 44,  47,  64, 216, 282, 247],
       [ 67,  67,   9, 297,  92,  75]])

Mathmetical operations on Numpy arrays

In [46]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [47]:
x*2

array([0, 2, 4, 6])

In [48]:
x+2

array([2, 3, 4, 5])

In [49]:
x**2

array([0, 1, 4, 9])

In [50]:
np.add(x, 2)

array([2, 3, 4, 5])

## Boolean Indexing

In [51]:
z

array([[85, 28, 43, 57,  5, 50],
       [26, 78, 40, 69, 70, 90],
       [63, 10, 67, 85, 11,  1],
       [82, 35, 22, 41, 24, 48],
       [42, 67,  7, 36, 75, 56]])

In [52]:
# I want to retrieve only the values that are greater than 50 from the upper array
z>50

array([[ True, False, False,  True, False, False],
       [False,  True, False,  True,  True,  True],
       [ True, False,  True,  True, False, False],
       [ True, False, False, False, False, False],
       [False,  True, False, False,  True,  True]])

In [53]:
z[z>50]

array([85, 57, 78, 69, 70, 90, 63, 67, 85, 82, 67, 75, 56])

In [54]:
np.exp(z)

array([[8.22301271e+36, 1.44625706e+12, 4.72783947e+18, 5.68572000e+24,
        1.48413159e+02, 5.18470553e+21],
       [1.95729609e+11, 7.49841700e+33, 2.35385267e+17, 9.25378173e+29,
        2.51543867e+30, 1.22040329e+39],
       [2.29378316e+27, 2.20264658e+04, 1.25236317e+29, 8.22301271e+36,
        5.98741417e+04, 2.71828183e+00],
       [4.09399696e+35, 1.58601345e+15, 3.58491285e+09, 6.39843494e+17,
        2.64891221e+10, 7.01673591e+20],
       [1.73927494e+18, 1.25236317e+29, 1.09663316e+03, 4.31123155e+15,
        3.73324200e+32, 2.09165950e+24]])

In [55]:
np.exp2(z)

array([[3.86856262e+25, 2.68435456e+08, 8.79609302e+12, 1.44115188e+17,
        3.20000000e+01, 1.12589991e+15],
       [6.71088640e+07, 3.02231455e+23, 1.09951163e+12, 5.90295810e+20,
        1.18059162e+21, 1.23794004e+27],
       [9.22337204e+18, 1.02400000e+03, 1.47573953e+20, 3.86856262e+25,
        2.04800000e+03, 2.00000000e+00],
       [4.83570328e+24, 3.43597384e+10, 4.19430400e+06, 2.19902326e+12,
        1.67772160e+07, 2.81474977e+14],
       [4.39804651e+12, 1.47573953e+20, 1.28000000e+02, 6.87194767e+10,
        3.77789319e+22, 7.20575940e+16]])

In [56]:
np.log(z)

array([[4.44265126, 3.33220451, 3.76120012, 4.04305127, 1.60943791,
        3.91202301],
       [3.25809654, 4.35670883, 3.68887945, 4.2341065 , 4.24849524,
        4.49980967],
       [4.14313473, 2.30258509, 4.20469262, 4.44265126, 2.39789527,
        0.        ],
       [4.40671925, 3.55534806, 3.09104245, 3.71357207, 3.17805383,
        3.87120101],
       [3.73766962, 4.20469262, 1.94591015, 3.58351894, 4.31748811,
        4.02535169]])

In [57]:
np.sum(z)

1413

In [58]:
np.var(z)

681.9566666666665

In [59]:
np.std(z, axis=0)

array([22.79122638, 25.20793526, 20.31157306, 18.01776901, 29.67153518,
       28.41126537])

In [60]:
np.min(z)

1

In [61]:
np.max(z)

90

In [62]:
np.argmin(z)

17

In [63]:
np.argmax(z)

11

## Here we start with the pandas library

In [64]:
# pandas is built on numpy library
# alot of modules are provided by pandas for data science

import pandas as pd
pd.__version__

'1.2.4'

### Pandas series

In [65]:
data = pd.Series([1,2,3,4,5,6])
data

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [66]:
data[1]

2

In [67]:
 data = pd.Series([10,20,30,40,50], index= list('abcde'), dtype='float', name= 'Example series')
 data

a    10.0
b    20.0
c    30.0
d    40.0
e    50.0
Name: Example series, dtype: float64

In [68]:
data.name

'Example series'

In [69]:
data.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [70]:
data.dtype

dtype('float64')

### dict

In [71]:
pop_dict = {'california': 123123,
            'Texas': 321321,
            'New york': 4546654,
            'Florida': 321321321
}
pop_dict

{'california': 123123,
 'Texas': 321321,
 'New york': 4546654,
 'Florida': 321321321}

In [72]:
pop_series = pd.Series(pop_dict)
pop_series

california       123123
Texas            321321
New york        4546654
Florida       321321321
dtype: int64

In [73]:
area_series = {'california': 45464,
            'Texas': 54644,
            'New york': 87954,
            'Florida': 65445
}

In [74]:
ser_area = pd.Series(area_series)
ser_area

california    45464
Texas         54644
New york      87954
Florida       65445
dtype: int64

In [75]:
df = pd.DataFrame({"Population": pop_series,
                    "Area": ser_area})
df

Population   Area
california      123123  45464
Texas           321321  54644
New york       4546654  87954
Florida      321321321  65445

In [76]:
df.columns

Index(['Population', 'Area'], dtype='object')

In [77]:
df.index

Index(['california', 'Texas', 'New york', 'Florida'], dtype='object')

In [78]:
df['Area']

california    45464
Texas         54644
New york      87954
Florida       65445
Name: Area, dtype: int64

In [79]:
np.random.seed(0)
arr = np.random.randint(0,100,(4,5))
arr

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88]])

In [80]:
df2 = pd.DataFrame(arr, index = list('abcd'), columns=['col1','col2','col3','col4','col5'])
df2

col1  col2  col3  col4  col5
a    44    47    64    67    67
b     9    83    21    36    87
c    70    88    88    12    58
d    65    39    87    46    88

### Slicing and indexing of pandas object

In [81]:
data = pd.Series(['a', 'b', 'c'], index= [1,2,3])
data

1    a
2    b
3    c
dtype: object

In [82]:
data.loc[1]

'a'

In [83]:
data.loc[2]

'b'

In [84]:
data.loc[1:3]

1    a
2    b
3    c
dtype: object

In [85]:
data.iloc[1]

'b'

In [86]:
data.iloc[1:3]

2    b
3    c
dtype: object

In [87]:
data.iloc[2]

'c'

In [88]:
df2['col1']

a    44
b     9
c    70
d    65
Name: col1, dtype: int64

In [89]:
df2.iloc[:3,:2]

col1  col2
a    44    47
b     9    83
c    70    88

In [90]:
df2.loc['a': 'c', 'col2': 'col4']

col2  col3  col4
a    47    64    67
b    83    21    36
c    88    88    12

In [91]:
df2[df2['col1']>50]

col1  col2  col3  col4  col5
c    70    88    88    12    58
d    65    39    87    46    88

## Loading the dataset

In [92]:
from sklearn.datasets import load_diabetes

In [93]:
data = load_diabetes()

In [94]:
x = data.data
y = data.target

In [95]:
df = pd.DataFrame(x, columns= data.feature_names)
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019908 -0.017646  
1   -0.039493 -0.068330 -0.092204  
2   -0.002592  0.002864 -0.025930  
3    0.034309  0.022692 -0.009362  
4   -0.002592 -0.031991 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018118  0.044485  
439 -0.011080 -0.046879  0.015491  
440  0.026560  0.044528 -0.025930  
441 -0.039493 -0.004220  0.003064  

[442 rows x 10 columns]

In [97]:
df.head() # retuns first five entries

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204  
2 -0.002592  0.002864 -0.025930  
3  0.034309  0.022692 -0.009362  
4 -0.002592 -0.031991 -0.046641

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB


In [100]:
df.describe() #descriptive stats

age           sex           bmi            bp            s1  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean  -3.634285e-16  1.308343e-16 -8.045349e-16  1.281655e-16 -8.835316e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.072256e-01 -4.464164e-02 -9.027530e-02 -1.123996e-01 -1.267807e-01   
25%   -3.729927e-02 -4.464164e-02 -3.422907e-02 -3.665645e-02 -3.424784e-02   
50%    5.383060e-03 -4.464164e-02 -7.283766e-03 -5.670611e-03 -4.320866e-03   
75%    3.807591e-02  5.068012e-02  3.124802e-02  3.564384e-02  2.835801e-02   
max    1.107267e-01  5.068012e-02  1.705552e-01  1.320442e-01  1.539137e-01   

                 s2            s3            s4            s5            s6  
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  
mean   1.327024e-16 -4.574646e-16  3.777301e-16 -3.830854e-16 -3.412882e-16  
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  
min   -1.156131e-01 -1.023071e-01 -7.639450e-02 -1.260974e-01 -1.377672e-01  
25%   -3.035840e-02 -3.511716e-02 -3.949338e-02 -3.324879e-02 -3.317903e-02  
50%   -3.819065e-03 -6.584468e-03 -2.592262e-03 -1.947634e-03 -1.077698e-03  
75%    2.984439e-02  2.931150e-02  3.430886e-02  3.243323e-02  2.791705e-02  
max    1.987880e-01  1.811791e-01  1.852344e-01  1.335990e-01  1.356118e-01

In [101]:
df['target'] = y

In [102]:
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019908 -0.017646   151.0  
1   -0.039493 -0.068330 -0.092204    75.0  
2   -0.002592  0.002864 -0.025930   141.0  
3    0.034309  0.022692 -0.009362   206.0  
4   -0.002592 -0.031991 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018118  0.044485   104.0  
439 -0.011080 -0.046879  0.015491   132.0  
440  0.026560  0.044528 -0.025930   220.0  
441 -0.039493 -0.004220  0.003064    57.0  

[442 rows x 11 columns]

In [104]:
df.to_csv('diabetes.csv', index= False)

In [106]:
df_diabetes = pd.read_csv('diabetes.csv')
df_diabetes

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019908 -0.017646   151.0  
1   -0.039493 -0.068330 -0.092204    75.0  
2   -0.002592  0.002864 -0.025930   141.0  
3    0.034309  0.022692 -0.009362   206.0  
4   -0.002592 -0.031991 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018118  0.044485   104.0  
439 -0.011080 -0.046879  0.015491   132.0  
440  0.026560  0.044528 -0.025930   220.0  
441 -0.039493 -0.004220  0.003064    57.0  

[442 rows x 11 columns]

### Operations on DataFrame

In [107]:
df_diabetes.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
437    False
438    False
439    False
440    False
441    False
Length: 442, dtype: bool

In [108]:
df_diabetes[df_diabetes.duplicated()]

Empty DataFrame
Columns: [age, sex, bmi, bp, s1, s2, s3, s4, s5, s6, target]
Index: []

In [109]:
df_diabetes.duplicated().sum()

0

In [113]:
df_diabetes.isnull().any()

age       False
sex       False
bmi       False
bp        False
s1        False
s2        False
s3        False
s4        False
s5        False
s6        False
target    False
dtype: bool

In [114]:
df_diabetes.isnull().any().any()

False

In [115]:
df_diabetes.isnull().sum()

age       0
sex       0
bmi       0
bp        0
s1        0
s2        0
s3        0
s4        0
s5        0
s6        0
target    0
dtype: int64

In [117]:
df_diabetes.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

In [119]:
df_diabetes['sex'].unique()

array([ 0.05068012, -0.04464164])

In [121]:
df_diabetes.groupby('sex').mean()

age       bmi        bp        s1        s2        s3  \
sex                                                                     
-0.044642 -0.007756 -0.003936 -0.010759 -0.001575 -0.006368  0.016923   
 0.050680  0.008805  0.004468  0.012215  0.001788  0.007229 -0.019212   

                 s4        s5        s6      target  
sex                                                  
-0.044642 -0.014826 -0.006693 -0.009291  149.021277  
 0.050680  0.016832  0.007598  0.010548  155.666667

In [124]:
df_diabetes.groupby('sex').agg([np.mean, max, min])

age                           bmi                      \
               mean       max       min      mean       max       min   
sex                                                                     
-0.044642 -0.007756  0.096197 -0.107226 -0.003936  0.160855 -0.084886   
 0.050680  0.008805  0.110727 -0.103593  0.004468  0.170555 -0.090275   

                 bp                            s1  ...        s4        s5  \
               mean       max       min      mean  ...       min      mean   
sex                                                ...                       
-0.044642 -0.010759  0.132044 -0.112400 -0.001575  ... -0.076395 -0.006693   
 0.050680  0.012215  0.107944 -0.084857  0.001788  ... -0.076395  0.007598   

                                     s6                          target  \
                max       min      mean       max       min        mean   
sex                                                                       
-0.044642  0.133599 -0.104365 -0.009291  0.135612 -0.137767  149.021277   
 0.050680  0.133599 -0.126097  0.010548  0.135612 -0.104630  155.666667   

                        
             max   min  
sex                     
-0.044642  346.0  25.0  
 0.050680  341.0  39.0  

[2 rows x 30 columns]

In [125]:
df_diabetes

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019908 -0.017646   151.0  
1   -0.039493 -0.068330 -0.092204    75.0  
2   -0.002592  0.002864 -0.025930   141.0  
3    0.034309  0.022692 -0.009362   206.0  
4   -0.002592 -0.031991 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018118  0.044485   104.0  
439 -0.011080 -0.046879  0.015491   132.0  
440  0.026560  0.044528 -0.025930   220.0  
441 -0.039493 -0.004220  0.003064    57.0  

[442 rows x 11 columns]

In [127]:
df_diabetes.reset_index() # index label to a column

index       age       sex       bmi        bp        s1        s2  \
0        0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821   
1        1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163   
2        2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194   
3        3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991   
4        4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596   
..     ...       ...       ...       ...       ...       ...       ...   
437    437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566   
438    438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165   
439    439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840   
440    440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283   
441    441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809   

           s3        s4        s5        s6  target  
0   -0.043401 -0.002592  0.019908 -0.017646   151.0  
1    0.074412 -0.039493 -0.068330 -0.092204    75.0  
2   -0.032356 -0.002592  0.002864 -0.025930   141.0  
3   -0.036038  0.034309  0.022692 -0.009362   206.0  
4    0.008142 -0.002592 -0.031991 -0.046641   135.0  
..        ...       ...       ...       ...     ...  
437 -0.028674 -0.002592  0.031193  0.007207   178.0  
438 -0.028674  0.034309 -0.018118  0.044485   104.0  
439 -0.024993 -0.011080 -0.046879  0.015491   132.0  
440 -0.028674  0.026560  0.044528 -0.025930   220.0  
441  0.173816 -0.039493 -0.004220  0.003064    57.0  

[442 rows x 12 columns]

In [138]:
df_copy = df_diabetes.copy()

In [139]:
df_copy

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019908 -0.017646   151.0  
1   -0.039493 -0.068330 -0.092204    75.0  
2   -0.002592  0.002864 -0.025930   141.0  
3    0.034309  0.022692 -0.009362   206.0  
4   -0.002592 -0.031991 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018118  0.044485   104.0  
439 -0.011080 -0.046879  0.015491   132.0  
440  0.026560  0.044528 -0.025930   220.0  
441 -0.039493 -0.004220  0.003064    57.0  

[442 rows x 11 columns]

In [140]:
df_copy.drop(['sex', 'age'], axis=1)

bmi        bp        s1        s2        s3        s4        s5  \
0    0.061696  0.021872 -0.044223 -0.034821 -0.043401 -0.002592  0.019908   
1   -0.051474 -0.026328 -0.008449 -0.019163  0.074412 -0.039493 -0.068330   
2    0.044451 -0.005671 -0.045599 -0.034194 -0.032356 -0.002592  0.002864   
3   -0.011595 -0.036656  0.012191  0.024991 -0.036038  0.034309  0.022692   
4   -0.036385  0.021872  0.003935  0.015596  0.008142 -0.002592 -0.031991   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.019662  0.059744 -0.005697 -0.002566 -0.028674 -0.002592  0.031193   
438 -0.015906 -0.067642  0.049341  0.079165 -0.028674  0.034309 -0.018118   
439 -0.015906  0.017282 -0.037344 -0.013840 -0.024993 -0.011080 -0.046879   
440  0.039062  0.001215  0.016318  0.015283 -0.028674  0.026560  0.044528   
441 -0.073030 -0.081414  0.083740  0.027809  0.173816 -0.039493 -0.004220   

           s6  target  
0   -0.017646   151.0  
1   -0.092204    75.0  
2   -0.025930   141.0  
3   -0.009362   206.0  
4   -0.046641   135.0  
..        ...     ...  
437  0.007207   178.0  
438  0.044485   104.0  
439  0.015491   132.0  
440 -0.025930   220.0  
441  0.003064    57.0  

[442 rows x 9 columns]

In [142]:
df_copy # the data still there? meaning its not dropped right away? yes! follow the next cells

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019908 -0.017646   151.0  
1   -0.039493 -0.068330 -0.092204    75.0  
2   -0.002592  0.002864 -0.025930   141.0  
3    0.034309  0.022692 -0.009362   206.0  
4   -0.002592 -0.031991 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018118  0.044485   104.0  
439 -0.011080 -0.046879  0.015491   132.0  
440  0.026560  0.044528 -0.025930   220.0  
441 -0.039493 -0.004220  0.003064    57.0  

[442 rows x 11 columns]

In [143]:
df_copy.drop(['sex', 'age'], axis=1, inplace=True) #inplace true will delete the data originally


In [144]:
df_copy.head()

bmi        bp        s1        s2        s3        s4        s5  \
0  0.061696  0.021872 -0.044223 -0.034821 -0.043401 -0.002592  0.019908   
1 -0.051474 -0.026328 -0.008449 -0.019163  0.074412 -0.039493 -0.068330   
2  0.044451 -0.005671 -0.045599 -0.034194 -0.032356 -0.002592  0.002864   
3 -0.011595 -0.036656  0.012191  0.024991 -0.036038  0.034309  0.022692   
4 -0.036385  0.021872  0.003935  0.015596  0.008142 -0.002592 -0.031991   

         s6  target  
0 -0.017646   151.0  
1 -0.092204    75.0  
2 -0.025930   141.0  
3 -0.009362   206.0  
4 -0.046641   135.0

### Other methods of Pandas DataFrame

In [146]:
# sorting by default is accending format
df_diabetes.sort_values(['bp', 'bmi'])

age       sex       bmi        bp        s1        s2        s3  \
224 -0.027310 -0.044642 -0.066563 -0.112400 -0.049727 -0.041397  0.000779   
41  -0.099961 -0.044642 -0.067641 -0.108957 -0.074494 -0.072712  0.015505   
93  -0.049105 -0.044642 -0.064408 -0.102071 -0.002945 -0.015406  0.063367   
84   0.001751 -0.044642 -0.039618 -0.100923 -0.029088 -0.030124  0.044958   
171 -0.020045 -0.044642 -0.046085 -0.098628 -0.075870 -0.059873 -0.017629   
..        ...       ...       ...       ...       ...       ...       ...   
408  0.063504 -0.044642 -0.050396  0.107944  0.031454  0.019354 -0.017629   
375  0.045341  0.050680 -0.002973  0.107944  0.035582  0.022485  0.026550   
350 -0.027310  0.050680  0.060618  0.107944  0.012191 -0.017598 -0.002903   
71  -0.001882 -0.044642  0.033673  0.125158  0.024574  0.026243 -0.010266   
340 -0.016412 -0.044642 -0.013751  0.132044 -0.009825 -0.003819  0.019187   

           s4        s5        s6  target  
224 -0.039493 -0.035817 -0.009362    77.0  
41  -0.039493 -0.049868 -0.009362    55.0  
93  -0.047243 -0.033249 -0.054925    96.0  
84  -0.050195 -0.068330 -0.129483    65.0  
171 -0.039493 -0.051401 -0.046641    74.0  
..        ...       ...       ...     ...  
408  0.023608  0.058039  0.040343   189.0  
375 -0.002592  0.028017  0.019633   217.0  
350 -0.002592  0.070211  0.135612   243.0  
71  -0.002592  0.026714  0.061054   270.0  
340 -0.039493 -0.035817 -0.030072   216.0  

[442 rows x 11 columns]

In [147]:
df_diabetes.sort_values(['bp', 'bmi'], ascending=False) # descending order

age       sex       bmi        bp        s1        s2        s3  \
340 -0.016412 -0.044642 -0.013751  0.132044 -0.009825 -0.003819  0.019187   
71  -0.001882 -0.044642  0.033673  0.125158  0.024574  0.026243 -0.010266   
350 -0.027310  0.050680  0.060618  0.107944  0.012191 -0.017598 -0.002903   
375  0.045341  0.050680 -0.002973  0.107944  0.035582  0.022485  0.026550   
408  0.063504 -0.044642 -0.050396  0.107944  0.031454  0.019354 -0.017629   
..        ...       ...       ...       ...       ...       ...       ...   
171 -0.020045 -0.044642 -0.046085 -0.098628 -0.075870 -0.059873 -0.017629   
84   0.001751 -0.044642 -0.039618 -0.100923 -0.029088 -0.030124  0.044958   
93  -0.049105 -0.044642 -0.064408 -0.102071 -0.002945 -0.015406  0.063367   
41  -0.099961 -0.044642 -0.067641 -0.108957 -0.074494 -0.072712  0.015505   
224 -0.027310 -0.044642 -0.066563 -0.112400 -0.049727 -0.041397  0.000779   

           s4        s5        s6  target  
340 -0.039493 -0.035817 -0.030072   216.0  
71  -0.002592  0.026714  0.061054   270.0  
350 -0.002592  0.070211  0.135612   243.0  
375 -0.002592  0.028017  0.019633   217.0  
408  0.023608  0.058039  0.040343   189.0  
..        ...       ...       ...     ...  
171 -0.039493 -0.051401 -0.046641    74.0  
84  -0.050195 -0.068330 -0.129483    65.0  
93  -0.047243 -0.033249 -0.054925    96.0  
41  -0.039493 -0.049868 -0.009362    55.0  
224 -0.039493 -0.035817 -0.009362    77.0  

[442 rows x 11 columns]